apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sb-app
  template:
    metadata:
      labels:
        app: sb-app
    spec:
      containers:
        - name: sb-crud
          image: salman1091/springboot-crud:latest 
          ports:
          - containerPort: 8081
