server:
  port: 8000
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    url: jdbc:h2:file:C:/Users/Eyes On Cloud/test;CACHE_SIZE=8192;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
