apiVersion: v1
kind: Service
metadata:
  name: springboot-k8sService
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 8081 #The port that the service is running on in the cluster
      targetPort: 8081 #The port exposed by the service
  type: LoadBalancer  #type of the service
