apiVersion: v1
kind: Service
metadata:
  name: sb-app-service
spec:
  selector:
    app: sb-app
  ports:
    - protocol: TCP
      port: 8081 #The port that the service is running on in the cluster
      targetPort: 8081 #The port exposed by the service
  type: LoadBalancer  #type of the service
  externalIPs: # Add this section to specify your host's IP address
    - 192.168.100.11 
